CREATE DATABASE IF NOT EXISTS stonkly;
USE stonkly;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tickers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_name VARCHAR(100) NOT NULL,
    sector VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS favorites (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    ticker_id INT NOT NULL,
    FOREIGN KEY (ticker_id) REFERENCES tickers(id),
    UNIQUE(username, ticker_id)
);

INSERT INTO tickers (company_name, sector) VALUES
("XLC","Telecom"),
("VOX","Telecom"),
("FCOM","Telecom"),
("IXP","Telecom"),
("IYZ","Telecom"),
("NXTG","Telecom"),
("XTL","Telecom"),
("RSPC","Telecom"),
("WBIF","Telecom"),
("LTL","Telecom"),

("XLU","Utilities"),
("PAVE","Utilities"),
("IGF","Utilities"),
("VPU","Utilities"),
("IFRA","Utilities"),
("NFRA","Utilities"),
("FUTY","Utilities"),
("FXU","Utilities"),
("IDU","Utilities"),
("UTES","Utilities"),
("GII","Utilities"),
("RSPU","Utilities"),
("JXI","Utilities"),
("OKLL","Utilities"),
("TOLZ","Utilities"),
("PUI","Utilities"),
("UTSL","Utilities"),
("RBLD","Utilities"),
("UPW","Utilities"),
("PSCU","Utilities"),
("INFR","Utilities"),
("EMIF","Utilities"),
("SDP","Utilities"),

("QQQ","Technology"),
("VGT","Technology"),
("XLK","Technology"),
("SMH","Technology"),
("IYW","Technology"),
("SOXX","Technology"),
("FTEC","Technology"),
("SOXL","Technology"),
("CIBR","Technology"),
("IGM","Technology"),
("KWEB","Technology"),
("IGV","Technology"),
("ARKK","Technology"),
("AIQ","Technology"),
("FDN","Technology"),
("IXN","Technology"),
("NVDL","Technology"),
("TECL","Technology"),
("RSPT","Technology"),
("TDIV","Technology"),
("XT","Technology"),
("SKYY","Technology"),
("QTUM","Technology"),
("CQQQ","Technology"),
("QTEC","Technology"),
("BULZ","Technology"),
("FNGU","Technology"),
("HACK","Technology"),
("ARKW","Technology"),
("XSD","Technology"),
("USD","Technology"),
("XNTK","Technology"),
("FXL","Technology"),
("BLOK","Technology"),
("ROBO","Technology"),
("CHAT","Technology"),
("BUG","Technology"),
("SOXS","Technology"),
("IVES","Technology"),
("IETC","Technology"),
("PSI","Technology"),
("IHAK","Technology"),
("ROM","Technology"),
("CONL","Technology"),
("PNQI","Technology"),
("NVDU","Technology"),
("AMDL","Technology"),
("SOXQ","Technology"),
("QQH","Technology"),
("FNGO","Technology"),
("IGPT","Technology"),
("DTCR","Technology"),
("WTAI","Technology"),
("MSTX","Technology"),
("BITQ","Technology"),
("FBL","Technology"),
("XSW","Technology"),
("PTF","Technology"),
("WGMI","Technology"),
("BKCH","Technology"),
("EMQQ","Technology"),
("DAPP","Technology"),
("FTXL","Technology"),
("STCE","Technology"),
("PSCT","Technology"),
("CWEB","Technology"),
("FDIG","Technology"),
("TRFK","Technology"),
("WCLD","Technology"),
("THNQ","Technology"),
("METV","Technology"),
("ALAI","Technology"),
("CLOU","Technology"),
("TDV","Technology"),
("MSFU","Technology"),
("GINN","Technology"),
("IPAY","Technology"),
("SMCX","Technology"),
("SNSR","Technology"),
("IONX","Technology"),
("AAPU","Technology"),
("LOUP","Technology"),
("SPRX","Technology"),
("OGIG","Technology"),
("APLY","Technology"),
("FBY","Technology"),
("SOCL","Technology"),
("CRPT","Technology"),
("IEUS","Technology"),
("IDGT","Technology"),
("WCBR","Technology"),
("FNGG","Technology"),
("SHOC","Technology"),
("BUZZ","Technology"),
("WEBL","Technology"),
("IZRL","Technology"),
("AVGX","Technology"),
("LEGR","Technology"),
("KLIP","Technology"),
("ISRA","Technology"),
("SARK","Technology"),
("AIPO","Technology"),
("FFND","Technology"),
("AIS","Technology"),
("ITEQ","Technology"),
("AGIX","Technology"),
("IBLC","Technology"),
("FCLD","Technology"),
("TECS","Technology"),
("XAIX","Technology"),
("DTEC","Technology"),
("XITK","Technology"),
("KOID","Technology"),
("MINV","Technology"),
("PRNT","Technology"),
("KTEC","Technology"),
("FNGD","Technology"),
("DRUP","Technology"),
("KQQQ","Technology"),
("INQQ","Technology"),
("IQM","Technology"),
("FMET","Technology"),
("KSTR","Technology"),
("KEMQ","Technology"),
("BLCN","Technology"),
("TCHI","Technology"),
("WISE","Technology"),
("NVDD","Technology"),
("KNCT","Technology"),
("LRNZ","Technology"),
("XPND","Technology"),
("WUGI","Technology"),
("TARK","Technology"),
("AIVC","Technology"),
("RIOX","Technology"),
("MST","Technology"),
("SEMI","Technology"),
("UBOT","Technology"),
("NVDS","Technology"),
("FMQQ","Technology"),
("MEME","Technology"),
("NBDS","Technology"),
("AAPB","Technology"),
("IBOT","Technology"),
("AAPD","Technology"),
("BCDF","Technology"),
("DGIN","Technology"),
("TIME","Technology"),
("SSG","Technology"),
("BERZ","Technology"),
("MNRS","Technology"),
("BIGY","Technology"),
("SATO","Technology"),
("AAPX","Technology"),
("GOOP","Technology"),
("TYLG","Technology"),
("WEBS","Technology"),
("BPAY","Technology"),
("AVGU","Technology"),
("BNGE","Technology"),
("IVRS","Technology"),
("BLKC","Technology"),
("MSFD","Technology"),
("DAT","Technology"),
("GAST","Technology"),
("BWEB","Technology"),
("MSFY","Technology"),
("VERS","Technology"),
("TINY","Technology"),
("AAPY","Technology"),
("UCYB","Technology"),
("XDAT","Technology"),
("REW","Technology"),
("PLT","Technology"),
("SPAM","Technology"),
("ARVR","Technology"),
("SKYU","Technology"),
("BULD","Technology"),
("CLOD","Technology"),
("BITW","Technology"),

("VNQ","Real Estate"),
("SCHH","Real Estate"),
("XLRE","Real Estate"),
("REET","Real Estate"),
("VNQI","Real Estate"),
("IYR","Real Estate"),
("USRT","Real Estate"),
("DFGR","Real Estate"),
("ICF","Real Estate"),
("RWR","Real Estate"),
("RWO","Real Estate"),
("FREL","Real Estate"),
("BBRE","Real Estate"),
("HAUZ","Real Estate"),
("REZ","Real Estate"),
("REM","Real Estate"),
("JPRE","Real Estate"),
("VGSR","Real Estate"),
("GQRE","Real Estate"),
("MORT","Real Estate"),
("RWX","Real Estate"),
("KBWY","Real Estate"),
("SRET","Real Estate"),
("SPRE","Real Estate"),
("FRI","Real Estate"),
("IYRI","Real Estate"),
("INDS","Real Estate"),
("CSRE","Real Estate"),
("RSPR","Real Estate"),
("LPRE","Real Estate"),
("IFGL","Real Estate"),
("DRN","Real Estate"),
("URE","Real Estate"),
("PSR","Real Estate"),
("BLDG","Real Estate"),
("REIT","Real Estate"),
("DRV","Real Estate"),
("NETL","Real Estate"),
("NURE","Real Estate"),
("PPTY","Real Estate"),
("SRS","Real Estate"),
("BYRE","Real Estate"),
("VRAI","Real Estate"),
("FPRO","Real Estate"),
("RDOG","Real Estate"),
("REK","Real Estate"),
("ERET","Real Estate"),
("RITA","Real Estate"),
("HAUS","Real Estate"),
("JRE","Real Estate"),

("XLY","Consumer Discretionary"),
("TSLL","Consumer Discretionary"),
("VCR","Consumer Discretionary"),
("FDIS","Consumer Discretionary"),
("IYC","Consumer Discretionary"),
("GGLL","Consumer Discretionary"),
("RXI","Consumer Discretionary"),
("ESPO","Consumer Discretionary"),
("XRT","Consumer Discretionary"),
("PEJ","Consumer Discretionary"),
("FXD","Consumer Discretionary"),
("AMZU","Consumer Discretionary"),
("TSLQ","Consumer Discretionary"),
("INCO","Consumer Discretionary"),
("RTH","Consumer Discretionary"),
("CHIQ","Consumer Discretionary"),
("RSPD","Consumer Discretionary"),
("BABX","Consumer Discretionary"),
("GGME","Consumer Discretionary"),
("IBUY","Consumer Discretionary"),
("HERO","Consumer Discretionary"),
("TRFM","Consumer Discretionary"),
("TSLS","Consumer Discretionary"),
("ONLN","Consumer Discretionary"),
("BETZ","Consumer Discretionary"),
("AMZZ","Consumer Discretionary"),
("EBIZ","Consumer Discretionary"),
("GAMR","Consumer Discretionary"),
("AWAY","Consumer Discretionary"),
("CARZ","Consumer Discretionary"),
("RETL","Consumer Discretionary"),
("FDRV","Consumer Discretionary"),
("IEDI","Consumer Discretionary"),
("PEZ","Consumer Discretionary"),
("MUSQ","Consumer Discretionary"),
("BJK","Consumer Discretionary"),
("WANT","Consumer Discretionary"),
("NERD","Consumer Discretionary"),
("TSLP","Consumer Discretionary"),
("PSCD","Consumer Discretionary"),
("TSL","Consumer Discretionary"),
("UCC","Consumer Discretionary"),
("AMZP","Consumer Discretionary"),
("GGLS","Consumer Discretionary"),
("NFLP","Consumer Discretionary"),
("AMZD","Consumer Discretionary"),
("BUYZ","Consumer Discretionary"),
("FLYU","Consumer Discretionary"),
("VICE","Consumer Discretionary"),
("OND","Consumer Discretionary"),
("ISHP","Consumer Discretionary"),
("ODDS","Consumer Discretionary"),
("CARU","Consumer Discretionary"),
("SCC","Consumer Discretionary"),
("EMTY","Consumer Discretionary"),
("BEDZ","Consumer Discretionary"),
("CARD","Consumer Discretionary"),
("FLYD","Consumer Discretionary"),
("TSLI","Consumer Discretionary"),

("XLP","Consumer Staples"),
("VDC","Consumer Staples"),
("IEV","Consumer Staples"),
("FSTA","Consumer Staples"),
("IYK","Consumer Staples"),
("KXI","Consumer Staples"),
("FXG","Consumer Staples"),
("ECON","Consumer Staples"),
("RSPS","Consumer Staples"),
("PBJ","Consumer Staples"),
("PSL","Consumer Staples"),
("PSCC","Consumer Staples"),
("WBIL","Consumer Staples"),
("FTXG","Consumer Staples"),
("UGE","Consumer Staples"),
("CLIX","Consumer Staples"),
("EATZ","Consumer Staples"),
("SZK","Consumer Staples"),

("XLE","Energy"),
("AMLP","Energy"),
("VDE","Energy"),
("NLR","Energy"),
("EMLP","Energy"),
("MLPX","Energy"),
("ICLN","Energy"),
("XOP","Energy"),
("IXC","Energy"),
("MLPA","Energy"),
("FENY","Energy"),
("IYE","Energy"),
("OIH","Energy"),
("TAN","Energy"),
("EIPI","Energy"),
("NUKZ","Energy"),
("AMJB","Energy"),
("TPYP","Energy"),
("PBW","Energy"),
("QCLN","Energy"),
("ATMP","Energy"),
("IEO","Energy"),
("RSPG","Energy"),
("FCG","Energy"),
("UMI","Energy"),
("AMZA","Energy"),
("ENFR","Energy"),
("FXN","Energy"),
("LCTD","Energy"),
("XES","Energy"),
("DRLL","Energy"),
("GUSH","Energy"),
("CNRG","Energy"),
("ERX","Energy"),
("MLPB","Energy"),
("FAN","Energy"),
("NZAC","Energy"),
("ERTH","Energy"),
("SMOG","Energy"),
("IEZ","Energy"),
("ACES","Energy"),
("FTXN","Energy"),
("PBD","Energy"),
("KWT","Energy"),
("HYDR","Energy"),
("USAI","Energy"),
("EINC","Energy"),
("PXE","Energy"),
("DIG","Energy"),
("PSCE","Energy"),
("PXI","Energy"),
("AMUB","Energy"),
("DRIP","Energy"),
("FRNW","Energy"),
("CTEC","Energy"),
("CRAK","Energy"),
("COAL","Energy"),
("NRGU","Energy"),
("PXJ","Energy"),
("RNRG","Energy"),
("URAN","Energy"),
("ERY","Energy"),
("DUG","Energy"),
("MLPR","Energy"),
("OILT","Energy"),
("VCLN","Energy"),
("NZUS","Energy"),
("SOLR","Energy"),
("CTEX","Energy"),
("RNWZ","Energy"),
("NRGD","Energy"),

("XLF","Financials"),
("VFH","Financials"),
("KBWB","Financials"),
("EUFN","Financials"),
("IYF","Financials"),
("KRE","Financials"),
("FAS","Financials"),
("FNCL","Financials"),
("FXO","Financials"),
("IYG","Financials"),
("IAI","Financials"),
("BIZD","Financials"),
("KBE","Financials"),
("DPST","Financials"),
("UYG","Financials"),
("KIE","Financials"),
("IAK","Financials"),
("IXG","Financials"),
("KCE","Financials"),
("IAT","Financials"),
("KBWD","Financials"),
("KBWP","Financials"),
("PSP","Financials"),
("DFNL","Financials"),
("RSPF","Financials"),
("FINX","Financials"),
("GREK","Financials"),
("PBDC","Financials"),
("FTXO","Financials"),
("FAZ","Financials"),
("QABA","Financials"),
("PHDG","Financials"),
("PFI","Financials"),
("VPC","Financials"),
("KBWR","Financials"),
("GABF","Financials"),
("ZIG","Financials"),
("BNKU","Financials"),
("HOOX","Financials"),
("PSCF","Financials"),
("GSIB","Financials"),
("BDCZ","Financials"),
("PEX","Financials"),
("SKF","Financials"),
("INDF","Financials"),
("SEF","Financials"),
("BDCX","Financials"),
("BNKD","Financials"),

("XLV","Healthcare"),
("VHT","Healthcare"),
("IBB","Healthcare"),
("XBI","Healthcare"),
("IHI","Healthcare"),
("IXJ","Healthcare"),
("IYH","Healthcare"),
("FHLC","Healthcare"),
("ARKG","Healthcare"),
("FBT","Healthcare"),
("PPH","Healthcare"),
("FXH","Healthcare"),
("IHF","Healthcare"),
("LABU","Healthcare"),
("RSPH","Healthcare"),
("IHE","Healthcare"),
("BBH","Healthcare"),
("PJP","Healthcare"),
("PINK","Healthcare"),
("PBE","Healthcare"),
("HIMZ","Healthcare"),
("CURE","Healthcare"),
("XPH","Healthcare"),
("PSCH","Healthcare"),
("XHE","Healthcare"),
("DNA","Healthcare"),
("PTH","Healthcare"),
("CNBS","Healthcare"),
("KURE","Healthcare"),
("CANC","Healthcare"),
("SBIO","Healthcare"),
("XHS","Healthcare"),
("RXL","Healthcare"),
("AGNG","Healthcare"),
("LABD","Healthcare"),
("BIB","Healthcare"),
("GNOM","Healthcare"),
("HTEC","Healthcare"),
("HRTS","Healthcare"),
("IBBQ","Healthcare"),
("BBP","Healthcare"),
("MEDI","Healthcare"),
("GDOC","Healthcare"),
("HELX","Healthcare"),
("BBC","Healthcare"),
("PSIL","Healthcare"),
("FTXH","Healthcare"),
("PILL","Healthcare"),
("FDHT","Healthcare"),
("BMED","Healthcare"),
("IBRN","Healthcare"),
("BIS","Healthcare"),
("EKG","Healthcare"),
("WDNA","Healthcare"),
("MDEV","Healthcare"),
("RXD","Healthcare"),

("XLI","Industrials"),
("ITA","Industrials"),
("PPA","Industrials"),
("VIS","Industrials"),
("AIRR","Industrials"),
("SHLD","Industrials"),
("XAR","Industrials"),
("PHO","Industrials"),
("FIW","Industrials"),
("FXR","Industrials"),
("IYJ","Industrials"),
("FIDU","Industrials"),
("EUAD","Industrials"),
("CGW","Industrials"),
("EXI","Industrials"),
("JETS","Industrials"),
("RSPN","Industrials"),
("IYT","Industrials"),
("ARKX","Industrials"),
("PRN","Industrials"),
("DFEN","Industrials"),
("PIO","Industrials"),
("MISL","Industrials"),
("RSHO","Industrials"),
("PSCI","Industrials"),
("UFO","Industrials"),
("XTN","Industrials"),
("FITE","Industrials"),
("EVX","Industrials"),
("NATO","Industrials"),
("HDGE","Industrials"),
("TBLU","Industrials"),
("BOAT","Industrials"),
("BDRY","Industrials"),
("DUSL","Industrials"),
("FTXR","Industrials"),
("AQWA","Industrials"),
("ROKT","Industrials"),
("JEDI","Industrials"),
("UXI","Industrials"),
("HAIL","Industrials"),
("TPOR","Industrials"),
("WAR","Industrials"),
("SEA","Industrials"),
("MOTO","Industrials"),
("SHPP","Industrials"),
("RFEU","Industrials"),
("EFRA","Industrials"),
("JETU","Industrials"),
("JETD","Industrials"),
("MAKX","Industrials"),
("SIJ","Industrials"),
("SUPL","Industrials"),

("GDX","Materials"),
("GDXJ","Materials"),
("XLB","Materials"),
("GUNR","Materials"),
("URA","Materials"),
("GRID","Materials"),
("SIL","Materials"),
("GNR","Materials"),
("COPX","Materials"),
("XME","Materials"),
("VAW","Materials"),
("SILJ","Materials"),
("ITB","Materials"),
("RING","Materials"),
("URNM","Materials"),
("XHB","Materials"),
("GDXU","Materials"),
("LIT","Materials"),
("REMX","Materials"),
("INFL","Materials"),
("NUGT","Materials"),
("PICK","Materials"),
("NANR","Materials"),
("IYM","Materials"),
("IGE","Materials"),
("NAIL","Materials"),
("MOO","Materials"),
("SGDM","Materials"),
("SLVP","Materials"),
("JNUG","Materials"),
("FMAT","Materials"),
("CCNR","Materials"),
("PKB","Materials"),
("SGDJ","Materials"),
("WOOD","Materials"),
("MXI","Materials"),
("FXZ","Materials"),
("HAP","Materials"),
("GOAU","Materials"),
("RSPM","Materials"),
("SLX","Materials"),
("SHNY","Materials"),
("GOEX","Materials"),
("DUST","Materials"),
("FTRI","Materials"),
("BATT","Materials"),
("VEGI","Materials"),
("GDXD","Materials"),
("PYZ","Materials"),
("CSNR","Materials"),
("CUT","Materials"),
("JDST","Materials"),
("HOMZ","Materials"),
("UYM","Materials"),
("DULL","Materials"),
("AUMI","Materials"),
("GMET","Materials"),
("SLJY","Materials"),
("PSCM","Materials"),
("DMAT","Materials"),
("NDIV","Materials"),
("SIMS","Materials"),
("KROP","Materials"),
("FTAG","Materials"),
("GBLD","Materials"),
("TINT","Materials"),
("SMN","Materials");